replicaCount: 1
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: false
image:
  repository: registry-nexus.trongnv.xyz/easy-rbac/easy-rbac
  tag: latest
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: nexus-registry-secret
serviceAccount:
  create: false
service:
  name: http
  type: ClusterIP
  port: 80
  targetPort: 80
  protocol: TCP
ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: "easy-rbac.trongnv.xyz"
      paths:
        - path: /
          pathType: Prefix
resources: {}
livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http
